# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16c9b1af51b75f793c00b68f8a7662bb5d7aeaf88ccacbc0005ba08bd1452a78c2abb7b05b07b8fa153c6a241d6b68047f27d00e63320744b119060d2ed3877d

test:
  secret_key_base: 58947be7ddd343a7ace3c26eb347f746ae90c5ed255bf8efb083792fd7b28df37bf4f189460eca82e7714fc79bc74ecf4258d706d42a4be7ab8632832f2cdc22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
